version: '3.6'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    ports:
      - 5500:5500

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - 3003:3000
    depends_on:
      - backend